### ISSUE TITLE
flywire/skeletonize.py possibly outdated

### ISSUE THREAD

**Issue by cheongh** [flyconnectome/fafbseg-py#5]
The use of the skeletonize_neuron() function in flywire/merge.py does not match its definition in flywire/skeletonize.py . The function definition has the input variable remove_soma_hairball and returns one variable, while the function usage in merge.py (line 88) has the input variable drop_soma_hairball and expects 3 variables returned.

**Comment by schlegelp** [comment]
Fixed with 964625c21f0d2526dd31a17863e309235deb9275.
